import { test, expect } from '@playwright/test';

var fishesPage = 'http://localhost:3000/fishes';

test.beforeAll(async () => {
    console.log("Before tests");
})

test.afterAll(async () => {
    console.log('After tests');
})

test.describe('Head tag area', () => {
    test("Contains the head tag an its content", async ({ page }) => {
        await page.goto(fishesPage);
        await expect(page).toHaveTitle('Some Fish');
        const metaDescription = page.locator('meta[name="description"]');
        await expect(metaDescription).toHaveAttribute('content', 'Generated by create next app');
        const linkIcon = page.locator('link[rel="icon"]');
        await expect(linkIcon).toHaveAttribute('href','/fish-favicon.png');
    })
})

test.describe('Main content tests', () => {
    test('Tests filter buttons count', async ({ page }) => {
        await page.goto(fishesPage);
        await expect(page.locator('li')).toHaveCount(27);
    })
})