import { test, expect } from '@playwright/test';

var homePage = 'http://localhost:3000/'

test.beforeAll(async () => {
    console.log("Before tests");
})

test.afterAll(async () => {
    console.log('After tests');
})

test.describe('Head tag area', () => {
    test("Contains the head tag an its content", async ({ page }) => {
        await page.goto(homePage);
        await expect(page).toHaveTitle('Home Page');
        const metaDescription = page.locator('meta[name="description"]');
        await expect(metaDescription).toHaveAttribute('content', 'Generated by create next app');
        const linkIcon = page.locator('link[rel="icon"]');
        await expect(linkIcon).toHaveAttribute('href','/fish-favicon.png');
    })
})

test.describe('Main content tests', () => {
    test('Contains header', async ({ page }) => {
        await page.goto(homePage);
        await expect(page.locator('h1')).toContainText("Fish Feeding");
    })

    test('Contains subheader', async ({ page }) => {
        await page.goto(homePage);
        await expect(page.locator('h2')).toContainText("This is a website about fish and what they eat.");
    })

    test('Contains button to Fishes page', async ({ page }) => {
        await page.goto(homePage);
        await expect(page.locator('button')).toContainText("View Fishes");
    })

    test('Contains image of fish', async ({ page }) => {
        await page.goto(homePage);
        await expect(page.locator('img')).toHaveCount(1);
    })
})