import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import Fishes from '../data/fishes.json'
import { useRouter } from 'next/router'
import { useEffect, useState } from 'react'
import fish from '../public/gold-fish.png'

export default function Home() {
  const r = useRouter();

  return (
    <div>
      <Head>
        <title>Home Page</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/fish-favicon.png" />
      </Head>
      
      <main className={styles.main}>
        <div className={styles.homeCont}>
          <div>
            <h1>Fish Feeding</h1>
            <h2>This is a website about fish and what they eat.</h2>
          </div>
          <Image className={styles.homeImage} id="homeImage"
            width={500} 
            src={fish} 
          />
          <button className="toFishesButton" id="toFishes" onClick={() => r.push("/fishes")}>View Fishes</button>
        </div>
      </main>
    </div>
  )
}
